language: node_js
node_js: --lts
cache:
  directories:
    - node_modules
branches:
  only:
    - hexo 
before_install:
  - npm install -g hexo-cli

install:
  - npm install
  - npm install hexo-deployer-git --save

# 执行清缓存，生成网页操作
script:
  - hexo clean
  - hexo generate
after_script:
  - git config user.name "scott-feng"
  - git config user.email "909698516@qq.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${Access_token}/g" ./_config.yml
  - hexo deploy
